name: 'autoreview'
description: 'automatically review PRs by delegating to the right ones'
inputs:
  github_token:
    description: 'API Token for Github'
    default: ${{ github.token }}
runs:
  using: "composite"
  steps:
    - name: "Autoreview"
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.github_token }}
      run: |
        curl -s --fail --retry 8 --header "Authorization: Bearer $GH_TOKEN" "${GITHUB_API_URL:-https://api.github.com}"/repos/"$GITHUB_REPOSITORY"/contributors | jq '.[].login' -r | jq -s '{ "reviewers": ., "team_reviewers": [] }' \
          | curl -s --fail --retry 8 --header "Authorization: Bearer $GH_TOKEN" "${GITHUB_API_URL:-https://api.github.com}"/repos/"$GITHUB_REPOSITORY"/pulls/"$number"/requested_reviewers -d @- 
